kind: Service
apiVersion: v1
metadata:
  name: sample-app-svc
  namespace: frontend
spec:
  type: LoadBalancer
#  loadBalancerIP: 104.199.190.226
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: sample-app
#    role: frontend